from ast import main
from openai import OpenAI

from financial_assistance.src.utils.load_config import CURRENT_PROJECT

# 初始化OpenAI客户端，使用ModelScope的API
client = OpenAI(
    api_key="ms-021ea8b4-3584-4e24-a5ab-f5f8fb666f15",  # ModelScope Token
    base_url="https://api-inference.modelscope.cn/v1"  # ModelScope API基础URL
)


def ge_llm_input(input_list):
    result = []
    cur_input = ""
    for input_item in input_list:
        if len(cur_input) + len(input_item) > CURRENT_PROJECT.get('max_token', 8000):
            result.append(cur_input)
            cur_input = ""
        cur_input += input_item
    if cur_input:
        result.append(cur_input)
    return result


def generate_messages(user_query: str) -> list:
    """
    生成用于调用LLM的消息列表
    
    参数:
        user_query: 用户的查询内容（字符串）
    
    返回:
        list: 消息列表，包含system和user角色的消息
             格式: [{'role': 'system', 'content': '...'}, {'role': 'user', 'content': '...'}]
    """
    # 构建消息列表
    messages = [
        {
            'role': 'system',  # 系统角色消息
            'content': '请帮我用中文markdown格式总结归纳'  # 系统提示内容You are a helpful assistant.
        },
        {
            'role': 'user',  # 用户角色消息
            'content': user_query  # 用户查询内容
        }
    ]
    
    # 返回消息列表
    return messages


def call_llm(messages: list) -> str:
    """
    调用大语言模型API，获取响应内容
    
    参数:
        messages: 消息列表，每个消息为字典格式，包含'role'和'content'字段
                 例如: [{'role': 'system', 'content': '...'}, {'role': 'user', 'content': '...'}]
    
    返回:
        str: 模型返回的完整响应内容
    """
    # 调用API创建聊天完成请求，使用流式输出
    response = client.chat.completions.create(
        model="Qwen/Qwen2.5-Coder-32B-Instruct",  # ModelScope模型ID
        messages=messages,  # 传入的消息列表
        stream=True  # 启用流式输出
    )
    
    # 初始化响应内容字符串
    full_content = ""
    
    # 遍历流式响应的每个chunk
    for chunk in response:
        # 获取当前chunk的内容（可能为None）
        delta_content = chunk.choices[0].delta.content
        # 如果内容不为None，则追加到完整响应中
        if delta_content is not None:
            full_content += delta_content
    
    # 返回完整的响应内容
    return full_content


if __name__ == "__main__":
    messages = generate_messages("""Skip to contentCreate Free AccountAbout PremiumExplore Alpha PicksNEW Virtual Analyst ReportFREE NewslettersHomeStock AnalysisStock IdeasMarket OutlookInvesting StrategyLong IdeasIPO AnalysisEditor's PicksCryptocurrencyMarket NewsTop Market NewsNotable CallsOn The MoveEnergy Stock NewsTech Stock NewsIPO NewsArtificial Intelligence (AI) NewsBudget & DOGE NewsMerger & Acquisition NewsMarket DataKey Market DataEarnings CalendarCurrenciesCryptocurrency PricesSectorsDividendsTop Dividend StocksTop Quant Dividend StocksDividend IdeasDividend Quick PicksDividend StrategyDividend News - FundsDividend News - StocksDividends DataETFsTop Rated ETFsETF StrategiesREITs & Real Estate ETFsCommodity ETFsEmerging Markets ETFsGrowth vs. Value ETFsBondsCountry ETFsEarningsEarnings CalendarEarnings Call TranscriptsEarnings Call InsightsEducationPodcastsVideosBlack Friday SaleInvesting GroupsExplore Investing GroupsPortfoliosCreate Portfolio+Portfolio Health CheckAbout PortfolioFind & CompareStock ScreenerAll StocksTop Rated StocksTop Growth StocksTop Value StocksTop Small Cap StocksStocks by QuantMost Shorted StocksStrong Buy Stocks - Short SqueezeTop REITsETF ScreenerAll ETFsTop Alternative ETFsTop Commodities ETFsTop International Equities ETFsTop Sector Equity ETFsTop U.S. Equity ETFsMost Shorted ETFsComparisonsAI Stocks5G StocksAerospace & Defense StocksDividend StocksValue StocksBlue Chip StocksFAANG StocksGold ETFsCash EquivalentsBig Bank StocksBig Pharma StocksRetail StocksSubscriptionsAlpha PicksPremium & ProGroup SubscriptionsHome page Seeking Alpha - Power to InvestorsCreate free accountSearch for Symbols, analysts, keywordsLog in本文有繁體中文翻譯版，請點此閱讀Earnings Call InsightsVerrica targets European expansion for YCANTH as Phase III programs advance and sales force growsNov. 17, 2025 10:37 AM ETVerrica Pharmaceuticals Inc. (VRCA) StockAI-Generated Earnings Calls Insights5ShareSavePlay(8min)CommentsEarnings Call Insights: Verrica Pharmaceuticals (VRCA) Q3 2025 Management View Jayson Rieger, President and CEO, highlighted several commercial, corporate, scientific, and regulatory milestones, emphasizing, "we've advanced our clinical programs in two of the highest unmet needs in dermatology for future development" and announced a global Phase III programSeeking Alpha's Disclaimer: The earnings call insights are compilations of earnings call transcripts and other content available on the Seeking Alpha website. The insights are generated by an AI tool and have not been curated or reviewed by editors. Due to inherent limitations in using AI-based tools, the accuracy, completeness, or timeliness of the earnings call insights cannot be guaranteed. Please see full earnings call transcripts here. The earnings call insights are intended for informational purposes only. Seeking Alpha does not take account of your objectives or your financial situation and does not offer any personalized investment advice. Seeking Alpha is not a licensed securities dealer, broker or US investment adviser or investment bank.SharePrintCommentsQuick InsightsHow is Verrica Pharmaceuticals' growth outlook influenced by YCANTH's regulatory progress and expansion?Verrica anticipates strong growth driven by YCANTH's advancing clinical milestones, upcoming EU filings, and expansion to new indications, bolstered by positive regulatory feedback and partnerships like with Torii Pharmaceutical.What were the main financial drivers behind Verrica Pharmaceuticals' Q3 2025 performance?Q3 results were primarily driven by $10.7 million in Torii milestone and collaboration revenue, alongside $3.6 million in net YCANTH revenue, with cost reductions and changes in product margin impacting overall profitability.What competitive and operational headwinds are impacting Verrica Pharmaceuticals' performance?Key challenges include seasonality affecting dispensed unit growth, competition from 'watch and wait' approaches, dependency on milestone payments, EU regulatory sequencing, and initial copay assistance investments.Recommended For YouWall Street Brunch: Nvidia WeekWall Street BreakfastS&P 500: From Shakeout To Takeoff (Technical Analysis)Andrew McElroyMy Most Contrarian Call Yet: Energy Is About To Rewrite Wall Street's PlaybookLeo NelissenThe Market Looks Strong, But It's Much Weaker Than You ThinkAgar CapitalBlue Owl Technology Finance: I'm Pivoting And Buying This 10%+ YielderRoberts Berzins, CFANebius: Wall Street's Blind SpotYiannis ZourmpanosAlphabet: Gemini 3.0 Is Coming, What's In PlayYR ResearchUPS: Dividend Panic Looks OverdoneDanil SeredaSomething Changed In OctoberSteven SavilleVYM: Why Vanguard's Popular $67B High Dividend Yield ETF Stands OutThe Sunday InvestorMore Trending NewsSee More »Create a free account to read the full articleAlready registered? Sign inCreate free accountBy creating an account using any of the options above, you agree to the Terms of Use & Privacy PolicyorContinue with GoogleSeeking Alpha - Power to InvestorsPower to InvestorsFollow usDownload appAccountAccount LoginManage My PortfolioPrivacyCreate PortfolioPortfolio Health CheckSubscriptionsPremium & ProAbout PremiumNEW Virtual Analyst ReportGroup SubscriptionsAlpha PicksAbout Alpha PicksFREE NewslettersTestimonialsInvesting GroupsLearn About Investing GroupsMost PopularFree TrialsTop RatedDividend InvestingValue InvestingOptions TradingGrowth StocksBiotech InvestingTech StocksQuantitative InvestingLearnInvesting ResourcesInvesting EducationInvesting StrategiesRetirement InvestingStock Market SectorsStock Market Holidays & HoursAfter Hours TradingPortfolio ManagementCryptocurrencyDividend InvestingPortfolio StrategyFixed IncomeRetirementIPO'sPodcastsVideo HubEventsEditors' PicksStock AnalysisStock IdeasLong IdeasStock Upgrades & DowngradesEditors' PicksQuick Picks & ListsEmerging MarketsStock ScreenerStocks by QuantTop StocksTop Quant Dividend StocksHigh Dividend Yield StocksTop Dividend StocksETFs & FundsETF ScreenerETF AnalysisETF GuideMutual FundsClosed End FundsEditors' PicksDividendsDividend Stock NewsREITsDividend IdeasDividend StrategyDividend Quick PicksEditors' PicksAnalysis by SectorEnergyCommunication ServicesReal EstateConsumer StaplesTechBasic MaterialsHealthcareConsumerUtilitiesFinancialsIndustrialsStock Comparison ToolsFAANG StocksGold ETFsCash EquivalentsBig Bank StocksBig Pharma StocksRetail StocksTop IndexesDow JonesS&P 500NasdaqGoldBitcoinMarket OutlookToday's MarketUS EconomyGold & Precious MetalsCommoditiesForexEditors' PicksCryptocurrencyMarket DataBond ETFsCommodity ETFsCountry ETFsCurrency ETFsDividend ETFsEmerging Market ETFsGlobal and Regional ETFsGrowth vs. Value ETFsMarket Cap ETFsReal Estate ETFsSector ETFsETF StrategiesSmart BetaThemes & Subsectors ETFsCryptocurrencyMarket NewsTop NewsTrending NewsOn the MoveMarket PulseGlobal MarketsNotable CallsBuybacksCommoditiesCryptocurrencyDebt/Share IssuanceDividends - StocksDividends - FundsGuidanceIPOsSPACsBudget & RegulationJobs & EmploymentPoliticsM&AUS EconomyWall Street BreakfastNews by SectorConsumerEnergyFinancialsHealthcareTechEarningsEarnings CalendarEarnings NewsEarnings AnalysisEarnings Calls TranscriptsContact usSubscription Support: subscriptions@seekingalpha.comContact UsAbout UsGroup SubscriptionsAffiliate ProgramCareersSitemapRSS FeedTerms Of UsePrivacyMarket Data Sources© 2025 Seeking AlphaTo ensure this doesn’t happen in the future, please enable Javascript and cookies in your browser.Is this happening to you frequently? Please report it on our feedback forum.If you have an ad-blocker enabled you may be blocked from proceeding. Please disable your ad-blocker and refresh.""")
    print(call_llm(messages))